# ********RoostGPT********
"""
Test generated by RoostGPT for test python_reflex using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=format_style_key_6b926aa24f
ROOST_METHOD_SIG_HASH=format_style_key_b48f9f607b


 1: Standard Style Key Conversion
Details:
  TestName: test_standard_style_key_conversion
  Description: Verify that a standard style key is correctly converted to camel case and mapped to its corresponding CSS name.
Execution:
  Arrange: No special setup required.
  Act: Call `format_style_key` with a standard style key, e.g., "background-color".
  Assert: The function should return a tuple with the corresponding CSS name, e.g., ("backgroundColor",).
Validation:
  Rationalize the importance of this test as it ensures the basic functionality of converting style keys to camel case and mapping them correctly.

"""

# ********RoostGPT********
from __future__ import annotations
from collections.abc import Mapping
from typing import Any, Literal
from reflex import constants
from reflex.components.core.breakpoints import Breakpoints, breakpoints_values
from reflex.event import EventChain, EventHandler, EventSpec, run_script
from reflex.utils import format
from reflex.utils.exceptions import ReflexError
from reflex.utils.imports import ImportVar
from reflex.utils.types import typehint_issubclass
from reflex.vars import VarData
from reflex.vars.base import LiteralVar, Var
from reflex.vars.function import FunctionVar
from reflex.vars.object import ObjectVar
from reflex.style import format_style_key
import pytest

class Test_StyleFormatStyleKey:

    @pytest.mark.valid
    def test_standard_style_key_conversion(self):
        # Arrange
        standard_style_key = "background-color"

        # Act
        result = format_style_key(standard_style_key)

        # Assert
        assert result == ("backgroundColor",)
